[package]
name = "laplade"
version = "0.1.4"
edition = "2021"
authors = ["laplade"]
description = "RPN(Reverse Polish Notatio) library"
license = "MIT"
include = ["src/", "README.md"]
homepage = "https://github.com/Laplade/liblary/tree/master/cargo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
